/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication24;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import org.apache.jena.query.QueryExecution;
import org.apache.jena.query.QueryExecutionFactory;
import org.apache.jena.query.QuerySolution;
import org.apache.jena.query.ResultSet;

/**
 *
 * @author Dayana
 */
public class ViewCentros extends javax.swing.JFrame {

    /**
     * Creates new form ViewCentros
     */
    String host = "http://localhost:8890/sparql";
    String graf = "http://centrosalud.org/data/encuestas_actividad";

    public ViewCentros() {
        initComponents();
        this.setLocationRelativeTo(this);
        ArrayList<String> typeArrayList = (ComboCentro());
        for (String string : typeArrayList) {
            cboSector.addItem(string);
        }
    }

//    SELECT DISTINCT ?s WHERE {
//?s a rdfs:Organization
//}
    public ArrayList<String> ComboCentro() {
        ArrayList<String> arrayList = new ArrayList<>();
        String centros = ""
                + "PREFIX v: <http://centrodesalud.org/ontology#> "
                + "SELECT DISTINCT?sec "
                + "FROM <" + graf + ">"
                + "WHERE { "
                + "?s v:organism ?o ."
                + "?o v:sector ?sec ."
                + "}";
        QueryExecution cboCentros = QueryExecutionFactory.sparqlService(host, centros);
        ResultSet results1 = cboCentros.execSelect();
        while (results1.hasNext()) {
            QuerySolution sol = results1.nextSolution();
            arrayList.add(String.valueOf(sol.getLiteral("sec")));
        }
        cboCentros.close();
        return arrayList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboCentro = new javax.swing.JComboBox<>();
        btnConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEsp = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblEncuesta = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboSector = new javax.swing.JComboBox<>();
        lbltipo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Centros de Salud");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 203, 34);

        jLabel2.setText("Selecione el centro de salud:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 85, 246, 23);

        cboCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCentroActionPerformed(evt);
            }
        });
        getContentPane().add(cboCentro);
        cboCentro.setBounds(10, 113, 416, 20);

        btnConsulta.setText("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsulta);
        btnConsulta.setBounds(10, 151, 92, 23);

        jScrollPane1.setViewportView(listEsp);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 406, 156);

        jLabel4.setText("Especialidades");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 69, 14);

        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 385, 77, 29);
        getContentPane().add(lblTipo);
        lblTipo.setBounds(97, 342, 296, 37);

        jLabel7.setText("Año de encuesta:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 432, 95, 35);
        getContentPane().add(lblAnio);
        lblAnio.setBounds(111, 432, 305, 35);

        jLabel8.setText("Fuente:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 485, 73, 35);
        getContentPane().add(lblEncuesta);
        lblEncuesta.setBounds(101, 479, 315, 41);

        jLabel9.setText("Seleccione el sector:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 60, 122, 14);

        cboSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSectorActionPerformed(evt);
            }
        });
        getContentPane().add(cboSector);
        cboSector.setBounds(160, 59, 266, 20);
        getContentPane().add(lbltipo1);
        lbltipo1.setBounds(120, 390, 260, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCentroActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        Especialidades();
        Tipo();
        Anio();
        Fuente();
    }//GEN-LAST:event_btnConsultaActionPerformed
    public void Especialidades() {
        ArrayList<String> arrayList = new ArrayList<>();
        String centroS = ""
                + "PREFIX v: <http://centrodesalud.org/ontology#> "
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> "
                + "SELECT Distinct?n ?s ?nombre "
                + "FROM <" + graf + ">"
                + "WHERE { "
                + "?s v:recordData ?o ."
                + "?s rdfs:name ?nombre ."
                + "?o rdfs:medicalSpecialty ?e ."
                + "?e rdfs:name ?n ."
                + "FILTER(?nombre= '" + ""
                + cboCentro.getSelectedItem().toString()
                + "') ."
                + "}";
        System.out.println("dato: " + cboCentro.getSelectedItem().toString());
        QueryExecution ex1 = QueryExecutionFactory.sparqlService(host, centroS);
        ResultSet results1 = ex1.execSelect();
        DefaultListModel modelList = new DefaultListModel<>();
        while (results1.hasNext()) {
            QuerySolution sol = results1.nextSolution();
            arrayList.add(String.valueOf(sol.getLiteral("n")));
        }
        listEsp.setModel(modelList);
        modelList.addElement(arrayList);
        ex1.close();

    }

    public void Tipo() {
        ArrayList<String> arrayList = new ArrayList<>();
        String centroT = ""
                + "PREFIX v: <http://centrodesalud.org/ontology#> "
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> "
                + "PREFIX dct: <http://purl.org/dc/terms/> "
                + "PREFIX dbo: <http://dbpedia.org/ontology/> "
                + "SELECT distinct?s ?tipo "
                + "FROM <" + graf + ">"
                + "WHERE { "
                + "?s dct:subject ?o ."
                + "?s rdfs:name ?nombre ."
                + "?o dbo:type ?tipo ."
                + "FILTER(?nombre= '" + ""
                + cboCentro.getSelectedItem().toString()
                + "') ."
                + "}";
        System.out.println(centroT);
        QueryExecution ex1 = QueryExecutionFactory.sparqlService(host, centroT);
        ResultSet results1 = ex1.execSelect();
        while (results1.hasNext()) {
            QuerySolution sol = results1.nextSolution();            
            String tipo = String.valueOf(sol.get("tipo"));
            System.out.println("tipo: "+tipo);
            lbltipo1.setText(tipo);
        }

        ex1.close();
    }

    public void Anio() {
        ArrayList<String> arrayList = new ArrayList<>();
        String centroA = ""
                + "PREFIX v: <http://centrodesalud.org/ontology#> "
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> "
                + "SELECT distinct?nombre ?f "
                + "FROM <" + graf + ">"
                + "WHERE { "
                + "?s v:recordData ?o ."
                + "?s rdfs:name ?nombre ."
                + "?o v:fecha ?f ."
                + "FILTER(?nombre= '" + ""
                + cboCentro.getSelectedItem().toString()
                + "') ."
                + "}";
        System.out.println(centroA);
        QueryExecution ex1 = QueryExecutionFactory.sparqlService(host, centroA);
        ResultSet results1 = ex1.execSelect();
        while (results1.hasNext()) {
            QuerySolution sol = results1.nextSolution();
            String anio = String.valueOf(sol.get("f"));
            lblAnio.setText(anio);
        }

        ex1.close();
    }

    public void Fuente() {
        ArrayList<String> arrayList = new ArrayList<>();
        String centroA = ""
                + "PREFIX v: <http://centrodesalud.org/ontology#> "
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> "
                + "SELECT distinct?nombre ?f "
                + "FROM <" + graf + ">"
                + "WHERE { "
                + "?s v:recordData ?o ."
                + "?s rdfs:name ?nombre ."
                + "?o v:fuente ?f ."
                + "FILTER(?nombre= '" + ""
                + cboCentro.getSelectedItem().toString()
                + "') ."
                + "}";
        System.out.println(centroA);
        QueryExecution ex1 = QueryExecutionFactory.sparqlService(host, centroA);
        ResultSet results1 = ex1.execSelect();
        while (results1.hasNext()) {
            QuerySolution sol = results1.nextSolution();
            String fuente = String.valueOf(sol.get("f"));
            lblEncuesta.setText(fuente);
        }

        ex1.close();
    }


    private void cboSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSectorActionPerformed
        ArrayList<String> typeArrayList = (CentroPorSector());
        ArrayList<String> listSpe = (CentroPorSector());
//        for (int i = 0; i < typeArrayList.size(); i++) {
//            while (null != typeArrayList.get(i)) {
//                String[] fields2 = typeArrayList.get(i).split(";");               
//                for (int j = 0; j < fields2.length; j++) {
//                    listSpe.add(fields2[i]);
//                }
//            }
//        }

        for (String string : typeArrayList) {
            cboCentro.addItem(string);
        }
    }//GEN-LAST:event_cboSectorActionPerformed

    //String opcion = cboSector.getSelectedItem().toString();
    public ArrayList<String> CentroPorSector() {
        ArrayList<String> arrayList = new ArrayList<>();
        String centro = ""
                + "PREFIX v: <http://centrodesalud.org/ontology#> "
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> "
                + "SELECT distinct?nombre ?sec "
                + "FROM <" + graf + ">"
                + "WHERE { "
                + "?s a rdfs:Organization ."
                + "?s rdfs:name ?nombre ."
                + "?s v:organism ?o ."
                + "?o v:sector ?sec ."
                + "FILTER(?sec= '" + ""
                + cboSector.getSelectedItem().toString()
                + "') ."
                + "}";
        QueryExecution ex1 = QueryExecutionFactory.sparqlService(host, centro);
        ResultSet results1 = ex1.execSelect();
        while (results1.hasNext()) {
            QuerySolution sol = results1.nextSolution();
            arrayList.add(String.valueOf(sol.getLiteral("nombre")));
        }
        ex1.close();
        return arrayList;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCentros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JComboBox<String> cboCentro;
    private javax.swing.JComboBox<String> cboSector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblEncuesta;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lbltipo1;
    private javax.swing.JList<String> listEsp;
    // End of variables declaration//GEN-END:variables
}
